version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017/LinkShortner

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3005:3005
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0.7
    ports:
      - 27017:27017
