version: '3'
services:
  frontend:
    container_name: short_frontend
    environment:
      - MONGO_URI=mongodb://mongodb:27017/LinkShortner
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    container_name: short_backend
    restart: always
    depends_on:
      - mongodb
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3005:3005

  mongodb:
    container_name: short_db
    image: mongo:5.0.7
    ports:
      - 27017:27017

networks:
  default:
    name: link_shortener_net
